package groupInDB

const bsonAllValues = "AL"
const bsonValueFreq = "vF"
const stats = "S"
const statType = "sT"
const baseStats = "bS"
const valueStats = "vS"
const lengthStats = "lS"
const valueFreqStats = "fS"
const valueHistogram = "vH"
const lengthHistogram = "lH"
const weekdayHistogram = "wH"
const hourHistogram = "hH"

const histogramDensity = "hd"
const histogramShift = "hs"
const histogramNormDensity = "nhd"
const histogramDivisor = "hdv"
const histogramConstants = "cs"
